[package]
name = "ferum"
version = "0.1.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }

[addresses]
ferum="0x728891241aa0dc576e23fa368c168f657b1364eb909c8444f28bc7e4a4a2268d"
